[docs sprint] using synthesizers docs update
ajar98/vocode-python pull request #8
Opened 2024-06-06 19:57 UTC by ajar98

2024-06-08 02:37 UTC, adnaans requested changes

2024-06-08 02:37 UTC, adnaans commented on docs/open-source/using-synthesizers.mdx
> +```
```suggestion
```python
```

2024-06-08 02:37 UTC, adnaans commented on docs/open-source/using-synthesizers.mdx
> +```
```suggestion
```python
```

2024-06-08 02:37 UTC, adnaans commented on docs/open-source/using-synthesizers.mdx
> +    user_id=os.getenv("PLAY_HT_USER_ID"),
we need to add `version='2'` right?

2024-06-10 19:00 UTC, ajar98 commented on docs/open-source/using-synthesizers.mdx
> +    user_id=os.getenv("PLAY_HT_USER_ID"),
it's defaulted

2024-06-12 19:54 UTC, adnaans approved these changes

2024-06-12 20:03 UTC, merged